name: Publish preview
on:
  pull_request:
  push:
    branches:
      - "master"
    tags:
      - "!**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Enable corepack
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm -r build

      - name: Publish
        run: pnpx pkg-pr-new publish './packages/*' './plugins/*' --no-template --pnpm --compact
